### ISSUE TITLE
"Config not found"

### ISSUE THREAD

**Issue by omerevren06** [antonioribeiro/google2fa-laravel#11]
if (is_null(config(Constants::CONFIG_PACKAGE_NAME))) {
            throw new \Exception('Config not found');
        }

![image](https://user-images.githubusercontent.com/10653711/30591030-ea352a54-9d49-11e7-93cd-366b92c7cffd.png)
laravel 5.5 "Config not found" what is the solution of the error

**Comment by antonioribeiro** [comment]
Have you run

    php artisan vendor:publish --provider=PragmaRX\\Google2FALaravel\\ServiceProvider

?

**Comment by omerevren06** [comment]
yes I did it. it did not work again.

**Comment by omerevren06** [comment]
php artisan vendor:publish --provider="PragmaRX\Google2FALaravel\ServiceProvider"
it worked fine when i run it like this. thank you for your interest.

**Comment by antonioribeiro** [comment]
Docs updated. Thanks for your feedback.

**Comment by ryryan** [comment]
I am getting this issue. Running latest version with 5.7. And used above code as per docs. Can't get around it. Any ideas?

**Comment by denrz** [comment]
> I am getting this issue. Running latest version with 5.7. And used above code as per docs. Can't get around it. Any ideas?

I have the same issue with Laravel 5.7. Did you find the solution?

**Comment by mbilgidhis** [comment]
I do have the same problem with Laravel 5.8. I have published the vendor, filled the providers and alias, restarted the server.
Does it support Laravel 5.8 yet?

**Comment by Isaac840** [comment]
> I do have the same problem with Laravel 5.8. I have published the vendor, filled the providers and alias, restarted the server.
> Does it support Laravel 5.8 yet?

I was also experiencing the same issue with Laravel 5.8. Here's what fixed it for me:

 > php artisan config:cache

**Comment by mbilgidhis** [comment]
> 
> @mbilgidhis I was also experiencing the same issue with Laravel 5.8. Here's what fixed it for me:
> 
> > php artisan config:cache

Thank you very much, it works like a charm
