### ISSUE TITLE
Error messages issue

### ISSUE THREAD

**Issue by amiranagram** [antonioribeiro/google2fa-laravel#117]
Hi, I don't have a particular issue with error messages, per se, but I would love to if you can move the error messages from config into a locale file. I have a multi language Laravel application and I need to return the error message in active language.

**Comment by PatrickJager** [comment]
I was trying to do a similar thing.
Our site is Dutch by default. If an error occurs (eg. invalid code has been entered) the error message from the package is in English. Our own part of the error is Dutch, which makes it confusing:
![image](https://user-images.githubusercontent.com/44800567/121177419-a8890d80-c85d-11eb-970c-d657ae578632.png)
I could make the whole message in Dutch/English, but that is not what we want. If the error messages where not in a config file it would help us.
