### ISSUE TITLE
Laravel 5.2 incompatibility middleware

### ISSUE THREAD

**Issue by blacksheepvision** [antonioribeiro/google2fa-laravel#12]
Hello dear mantainer,

Installed the library but when I try to access a route protected by 2fa middleware i get :

```
FatalErrorException in OneTimePasswordRequested.php line 11:
Trait 'Illuminate\Foundation\Events\Dispatchable' not found
```

Thanks for your efforts I hope it gets fixed. Thanks

:1st_place_medal:

**Comment by dhaileytaha** [comment]
Were you able to resolve the error.?? Because i am also getting the exact same error. 
Please guide

**Comment by jorgearmando93** [comment]
ok you can change the call the method in laravel config/app.php

2017-10-24 10:11 GMT-04:00 dhaileytaha <notifications@github.com>:

**Comment by dhaileytaha** [comment]
Change to what ? Can you please specify ?

**Comment by hostcoinwallet** [comment]
@jorgearmando93 Please help. What to do. I am sorry to trouble you but i am getting the same error.
@blacksheepvision  if u could help too

**Comment by jorgearmando93** [comment]
in providers
PragmaRX\Google2FALaravel\ServiceProvider::class,
in aliases
'Google2FA' => PragmaRX\Google2FALaravel\Facade::class,

**Comment by ldt1992** [comment]
@antonioribeiro Can you help us ? I am getting the same error.

**Comment by ldt1992** [comment]
@antonioribeiro can you give us source code of demo middleware google 2fa in readme to ref, please ?

**Comment by antonioribeiro** [comment]
This package was supposed to be 5.4+ only:

**Comment by antonioribeiro** [comment]
Version tagged.

**Comment by renatorf** [comment]
Hello @antonioribeiro!  The requirements said PHP 5.4+ but I guess the problem is with LARAVEL 5.2. I'm having the same problem and I'm on PHP 7.0. 

Did anyone find a fix?
