### ISSUE TITLE
You need to install the imagick extension to use this back end

### ISSUE THREAD

**Issue by GustaveTsopmo** [antonioribeiro/google2fa-laravel#137]
**You need to install the imagick extension to use this back end**
Hello. I am using Laravel 7.x, and i am facing this problem after installing. Please help me. thank

**Comment by JayDijkstra** [comment]
I have the same error on my applications (Laravel 6.x). What seems to work for me is downgrading BaconQr. https://github.com/Bacon/BaconQrCode/issues/60. Don't know if this will get fixed within this package.

**Comment by antonioribeiro** [comment]
Just tagged 2.0 (because of breaking changes) to use the an updated version of Google2FA QRCode package.
