### ISSUE TITLE
Call to undefined method PragmaRX\Google2FALaravel\Google2FA::getQRCodeInline

### ISSUE THREAD

**Issue by efcjunior** [antonioribeiro/google2fa-laravel#139]
What could I be doing wrong?

Composer file:

...
"laravel/framework": "5.6.*",
"pragmarx/google2fa-laravel": "^0.2.0",
"php": "^7.1.3",
"bacon/bacon-qr-code": "1.0.3",
...

Controller:

$google2fa = app('pragmarx.google2fa');
        $QR_Image = $google2fa->getQRCodeInline(
            config('app.name'),
            $admin->email,
            $admin->google2fa_secret
        );

**Comment by mfn** [comment]
>  "pragmarx/google2fa-laravel": "^0.2.0",

Latest release is 1.4.1…
