### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jorgearmando93** [antonioribeiro/google2fa-laravel#14]

**Comment by jorgearmando93** [comment]
i have problem with thios command
php artisan vendor:publish --provider=PragmaRX\\Google2FALaravel\\ServiceProviderphp artisan vendor:publish --provider=PragmaRX\\Google2FALaravel\\ServiceProvider

**Comment by omerevren06** [comment]
try the following
php artisan vendor:publish --provider="PragmaRX\Google2FALaravel\ServiceProvider"

**Comment by antonioribeiro** [comment]
Please try it this way:

    php artisan vendor:publish --provider="PragmaRX\Google2FALaravel\ServiceProvider"

**Comment by antonioribeiro** [comment]
@omerevren06 thanks, looks like we sent it almost at the same time
