### ISSUE TITLE
BaconQrCode

### ISSUE THREAD

**Issue by jguomz** [antonioribeiro/google2fa-laravel#148]
Is it posible update BaconQrCode 1.0.3 to 2?

**Comment by antonioribeiro** [comment]
It is already if you look here: https://github.com/antonioribeiro/google2fa-qrcode/blob/master/composer.json#L20

I just created a new app to install it and it's 2.0:

<img width="967" alt="Screenshot 2021-08-15 at 13 05 27" src="https://user-images.githubusercontent.com/3182864/129476339-f3146fbe-6006-4977-908d-1546b612808a.png">
