### ISSUE TITLE
Session resets automatically 

### ISSUE THREAD

**Issue by qadirp** [antonioribeiro/google2fa-laravel#151]
Hi,
I have 2 laravel projects running on a single login system having session in redis when I switch to files for the session 2fa works fine but when I use redis and I visit one project to another 2fa session resets and it asks for the code every time I switch back and forth from the application

**Comment by antonioribeiro** [comment]
If you look closely at the you will see that this package is only using session (get/put, check the Session trait), being on Redis, file or any other storage, if your session is resetting, it's something on your app and you probably need Laravel help.
