### ISSUE TITLE
New release with bugs fixed

### ISSUE THREAD

**Issue by nicStuff** [antonioribeiro/google2fa-laravel#16]
Hello, please consider making a new release with this https://github.com/antonioribeiro/google2fa-laravel/commit/e47853074381e038d19aad91b11da878da632747#diff-20ebc1864ccff7f0bb90a07bd850e888 correction: I've spent hours finding it myself for then seeing that it's already fixed on bleeding edge.

Thank you

**Comment by andyvenus** [comment]
+1 - I also just wasted a bit of time wondering why this didn't work

**Comment by antonioribeiro** [comment]
Sorry for the delay, guys, version 0.1.3 just tagged.

**Comment by andyvenus** [comment]
No worries, thanks @antonioribeiro
