### ISSUE TITLE
OneTimePasswordRequestedL53 not found

### ISSUE THREAD

**Issue by cargix1** [antonioribeiro/google2fa-laravel#17]
Hi Antoni,

It appears we maybe missing a class. I'm trying to use your package on Laravel 5.3 and getting the following error: 

```
Class 'PragmaRX\Google2FALaravel\Support\OneTimePasswordRequestedL53' not found in /srv/app/htdocs/vendor/pragmarx/google2fa-laravel/src/Support/Response.php:67 
```

It appears `makeRequestOneTimePasswordResponse` is calling `OneTimePasswordRequestedL53` within src/Support/Response.php but no event for OneTimePasswordRequestedL53 exists. 

Thanks,

Andy

**Comment by antonioribeiro** [comment]
Should be fixed now.
