### ISSUE TITLE
installation failed in Laravel 5.2

### ISSUE THREAD

**Issue by gustavosz** [antonioribeiro/google2fa-laravel#171]
Hi, i am trying to install any version of this library in laravel 5.2 and it always fails.

I tried with the following commands

composer require pragmarx/google2fa-laravel:^1.0|^2.0|^3.

Return error:

Problem 1
    - pragmarx/google2fa-laravel v1.0.0 requires laravel/framework >=5.5 -> found laravel/framework[v5.5.0, ..., v5.8.38, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.15, v9.0.0, ..., v9.15.0] but it conflicts with your root composer.json require (5.2.*).
    - pragmarx/google2fa-laravel[v1.0.1, ..., v1.3.4] require laravel/framework >=5.4.36 -> found laravel/framework[v5.4.36, ..., v5.8.38, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.15, v9.0.0, ..., v9.15.0] but it conflicts with your root composer.json require (5.2.*).
    - pragmarx/google2fa-laravel[v1.4.0, ..., v1.4.1] require laravel/framework >=5.4.36|^8.0 -> found laravel/framework[v5.4.36, ..., v5.8.38, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.15, v9.0.0, ..., v9.15.0] but it conflicts with your root composer.json require (5.2.*).
    - Root composer.json requires pragmarx/google2fa-laravel ^1.0 -> satisfiable by pragmarx/google2fa-laravel[v1.0.0, ..., v1.4.1].

**Comment by nicolaspennesi** [comment]
Same here! The readme says that version >= 2.0.0 should work on Laravel 5.2 but it asks me for >= 5.4.

There is any workaround to use the library on 5.2?

**Comment by mfn** [comment]
> laravel 5.2

Check out https://packagist.org/packages/pragmarx/google2fa-laravel#v0.3.0 ; it seems that was the last version supported 5.2.

Try `composer require pragmarx/google2fa-laravel:0.3.0`

HTH
