### ISSUE TITLE
Class "path.storage" does not exist in ../../api/vendor/laravel/framework/src/Illuminate/Container/Container.php:873

### ISSUE THREAD

**Issue by amrshakya** [antonioribeiro/google2fa-laravel#172]
I'm currently using laravel lumen version 8+ and after i install this lib i get the following error.

`Uncaught ReflectionException: Class "path.storage" does not exist in /var/www/credit-api/vendor/laravel/framework/src/Illuminate/Container/Container.php:873
Stack trace:
#0 /var/www/credit-api/vendor/laravel/framework/src/Illuminate/Container/Container.php(873): ReflectionClass->__construct('path.storage')
#1 /var/www/credit-api/vendor/laravel/framework/src/Illuminate/Container/Container.php(754): Illuminate\Container\Container->build('path.storage')
#2 /var/www/credit-api/vendor/laravel/framework/src/Illuminate/Container/Container.php(692): Illuminate\Container\Container->resolve('path.storage', Array)
#3 /var/www/credit-api/vendor/laravel/lumen-framework/src/Application.php(300): Illuminate\Container\Container->make('path.storage', Array)
#4 /var/www/credit-api/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(119): Laravel\Lumen\Application->make('path.storage', Array)
#5 /var/www/credit-api/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(790): app('path.storage')
#6 /var/www/credit-api/config/excel.php(292): storage_path('framework/larav...')
#7 /var/www/credit-api/vendor/laravel/lumen-framework/src/Application.php(688): require('/var/www/credit...')
#8 /var/www/credit-api/bootstrap/app.php(66): Laravel\Lumen\Application->configure('excel')
#9 /var/www/credit-api/public/index.php(14): require('/var/www/credit...')
#10 {main}`

**Comment by mfn** [comment]
Your problem lies with excel, not google2fa?

> ```
> #5 /var/www/credit-api/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(790): app('path.storage')
> #6 /var/www/credit-api/config/excel.php(292): storage_path('framework/larav...')
> #7 /var/www/credit-api/vendor/laravel/lumen-framework/src/Application.php(688): require('/var/www/credit...')
> 
> ```

**Comment by amrshakya** [comment]
@mfn Yes i think the same the problem lies within excel but this only happens after i install google2fa-laravel version. Even if i just install google2fa it works fine.

**Comment by amrshakya** [comment]
> Your problem lies with excel, not google2fa?
> 
> > ```
> > #5 /var/www/credit-api/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(790): app('path.storage')
> > #6 /var/www/credit-api/config/excel.php(292): storage_path('framework/larav...')
> > #7 /var/www/credit-api/vendor/laravel/lumen-framework/src/Application.php(688): require('/var/www/credit...')
> > ```
@mfn Yes i think the same the problem lies within excel but this only happens after i install google2fa-laravel version. Even if i just install google2fa it works fine.

**Comment by mfn** [comment]
> Even if i just install google2fa it works fine.

To me that sounds like the problem lies outside.

Is the excel package properly supposed on Lumen? Anyhow, you should [open an issue there](https://github.com/SpartnerNL/Laravel-Excel) I believe.

**Comment by amrshakya** [comment]
@mfn I think i'll close this issue from here as i stopped using this lib of laravel and directly use gogole2fa. Since the issue generate seems too be from excel i don't think it is relevant to keep the issue open.
