### ISSUE TITLE
Error handling when an OTP is about to expire

### ISSUE THREAD

**Issue by harmanlgz** [antonioribeiro/google2fa-laravel#19]
When I enter an OTP( Google Authenticator App) that is about to expire, I get MethodNotAllowedHttpException from 2faVerify function. How to handle an **OTP that is about to expire**?

**Comment by antonioribeiro** [comment]
Could you provide a way for us to reproduce this, please?

**Comment by markgukov** [comment]
It can be reproduced by entering an OTP that just expired a second ago.

**Comment by markgukov** [comment]
@antonioribeiro not sure if you saw my comment above.
