### ISSUE TITLE
Session store not set on request.

### ISSUE THREAD

**Issue by eo22** [antonioribeiro/google2fa-laravel#27]
I follow all steps of inst., but after clicking "Validate" it shows this error "Session store not set on request."

**Comment by DanEdney** [comment]
also having this issue

**Comment by noplanman** [comment]
I'm getting this when writing tests, and was wondering what the fix was.

**Comment by mercrover** [comment]
For stateless make sure you set stateless to `true`
e.g ` $google2fa->setStateless(true)->login()`

**Comment by jonathanpmartins** [comment]
If you are using sanctum put your domain in the `stateful` configuration of the `sanctum.php` file.

```php
'stateful' => explode(',', env('SANCTUM_STATEFUL_DOMAINS', sprintf(
    '%s%s',
    'localhost,localhost:3000,127.0.0.1,127.0.0.1:8000,::1,'.$_SERVER['HTTP_HOST'],
    Sanctum::currentApplicationUrlWithPort(),
))),
```
