### ISSUE TITLE
Using with SPA and Laravel as a stateless API.

### ISSUE THREAD

**Issue by ibrunotome** [antonioribeiro/google2fa-laravel#29]
Hi! I already used this great package on another project, but this current project is a stateless Laravel application consumed by a vue.js front with jwt, there is no session, so my code breaks in the Google2FA file in the methods that use session.

What kind of modifications do you recommend to me @antonioribeiro?

**Comment by fernandocoronatomf** [comment]
@ibrunotome Wanting to implement this on a vue.js SPA as well... any ideas?

**Comment by ibrunotome** [comment]
Nothing yet, using without google 2FA for now.

**Comment by velegip** [comment]
i've made some changes on my fork. @antonioribeiro can you check?
https://github.com/velegip/google2fa-laravel

**Comment by antonioribeiro** [comment]
Yeah, sorry for not answering it before... I would go with pure Google2FA or [Google2FA-QRCode](https://github.com/antonioribeiro/google2fa-qrcode).

**Comment by vanushwashere** [comment]
Hey, first I want to thank you for a great package.
And second I noticed that there is an update with support of stateless auth.
The documentation is very poor, it's just says that I need to use another middleware, but where I have to put it ? And how have to be the whole API Auth process ? Should I send it on login request with login and pass, or should I protect other routes except login, so client need to send otp with token to access them? Can you or someone please explain or provide an example of that? 
I am using Laravel 5.4 with Laravel Passport.
Thanks in advance  :)

**Comment by kakajansh** [comment]
> Hey, first I want to thank you for a great package.
> And second I noticed that there is an update with support of stateless auth.
> The documentation is very poor, it's just says that I need to use another middleware, but where I have to put it ? And how have to be the whole API Auth process ? Should I send it on login request with login and pass, or should I protect other routes except login, so client need to send otp with token to access them? Can you or someone please explain or provide an example of that?
> I am using Laravel 5.4 with Laravel Passport.
> Thanks in advance :)

Hi! Could you find a way?

**Comment by vanushwashere** [comment]
I come up with just calling `$google2fa->verifyKey($secret, $token, config('google2fa.window')` in my LoginController method, I didn't used middleware.

**Comment by buzzclue** [comment]
You should make your own middleware and use that in Kernel.php, Something like this:

```php
namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use PragmaRX\Google2FALaravel\Support\Authenticator;
use PragmaRX\Google2FALaravel\Events\OneTimePasswordRequested;

class TwoFAMiddleware
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle(Request $request, Closure $next)
    {
        $authenticator = app(Authenticator::class)->boot($request);

        if ($authenticator->isAuthenticated()) {
            return $next($request);
        }

        return $this->makeRequestOneTimePasswordResponse();
    }

    /**
     * Create a response to request the OTP.
     *
     * @return \Illuminate\Http\Response|\Illuminate\Http\JsonResponse
     */
    public function makeRequestOneTimePasswordResponse()
    {
        event(new OneTimePasswordRequested(auth()->user()));

        return redirect()->route('authtwofa');
    }
}
```

I am using InertiaJs so the redirect works fine for me you can change the redirect in makeRequestOneTimePasswordResponse depending on your SPA framework.

**Comment by MuhammadSulman** [comment]
OneTimePasswordRequested:- I am expecting a listener here and it's implementations.
