### ISSUE TITLE
Show error message to user in view

### ISSUE THREAD

**Issue by Sebi94nbg** [antonioribeiro/google2fa-laravel#31]
Is there any variable, which I can use in the view to show a error message?

Eg. the user tries to login, but due of an wrong or expired OTP, the 2FA fails. So in this case, I would like to show the user a message like "used OTP expired" or simply "Used OTP was invalid".

In the `config/google2fa.php` you can already define an error message:
https://github.com/antonioribeiro/google2fa-laravel/blob/7bdf97dbc75d319f0c621a41cd83f17dd1f23042/src/config/config.php#L61-L66

But how can I indicate, that the user has tried to login in order to show this message?

I can show the text in the view like this: `{{ config('google2fa.error_messages.wrong_otp') }}`

**Comment by NibeP** [comment]
I would like to know this too.

**Comment by candro** [comment]
Use the default output of errors
```
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
```

**Comment by marknuyens** [comment]
I can't seem to get this working either.

**Comment by Sebi94nbg** [comment]
@marknuyens this is, how my view code looks like:
```
@if (!$errors->isEmpty())
    <div class="alert alert-info col-md-10">        
        {{ config('google2fa.error_messages.wrong_otp') }}
    </div>
@endif

<form class="form-horizontal" method="POST" action="{{ route('dashboard') }}" name="one_time_password">
    {{ csrf_field() }}

    <div class="form-group{{ $errors->has('one_time_password') ? ' has-error' : '' }}">
        <label for="one_time_password" class="col-md-4 control-label">{{ trans('auth/google2fa.input_headline_password') }}</label>

        <div class="col-md-6">
            <input id="one_time_password" min="0" max="999999" step="1" type="number" class="form-control" name="one_time_password">

            @if ($errors->has('one_time_password'))
                <span class="help-block">
                    <strong>{{ $errors->first('one_time_password') }}</strong>
                </span>
             @endif
        </div>
    </div>
</form>
```
It's returning the message in case of an incorrect entered OTP (blue area):
![Error Message in Browser View](https://i.imgur.com/dtPsvcr.png)

But if you have multiple error message variables in your `config/google2fa.php`, this is may not the best solution.

Any improvements are welcome.

**Comment by marknuyens** [comment]
@Sebi94nbg I see now, thanks. 👍 -- Before, I was using the key name from the config file, i.e. "[wrong_otp]". Not sure where this var is used for then.

**Comment by Adam-78** [comment]
<div class="form-group @if ($errors->has('message')) has-error @endif">
           {!! Form::label('one_time_password', 'Code') !!}
           {!! Form::text('one_time_password', null, ['class' => 'form-control']) !!}
           @if ($errors->has('message')) <p  class="help-block">{{ $errors->first('message') }}</p> @endif  
    </div>
