### ISSUE TITLE
BaconQR v2 not working

### ISSUE THREAD

**Issue by it-can** [antonioribeiro/google2fa-laravel#32]
I get this error when trying to use BaconQRCode v2.

```
Class 'BaconQrCode\Renderer\Image\Png' not found
```

v2.0 was refactored and doesnt include the PNG renderer anymore.

this version works...
```
composer require bacon/bacon-qr-code 1.0.3
```

**Comment by ixperiencenl** [comment]
@it-can Thanks for this update. Think this package needs an update that keeps it working with the new version.

**Comment by sergiq** [comment]
As I mentioned in a duplicated issue this lib should requires the library in a certain revision range (^1.0.0).
[PR45](https://github.com/antonioribeiro/google2fa-laravel/pull/45)

**Comment by sergiq** [comment]
@it-can, Is this issue solved?

**Comment by sergiq** [comment]
@it-can the main problems is that google2fa-laravel is requering the last version of BaconQrCode

**Comment by sergiq** [comment]
Is it hard to understand that the composer.json is wrong @it-can ? Do I have to upload a new "duplicate" package (packagist) only for fix a simple line? Could you say anything @ixperiencenl?

**Comment by it-can** [comment]
I implemented my own qr code generator with ```chillerlan/php-qrcode```

**Comment by imranrbx** [comment]
i just tested with laravel 5.7 qrcode ^1.0 with google2fa-laravel as google2fa-laravel only support upt v1.0 and v2 have different files and structure, v2 doesn't include png class it have image writer
