### ISSUE TITLE
Error: The payload is invalid.

### ISSUE THREAD

**Issue by brvnks** [antonioribeiro/google2fa-laravel#35]
Hi again, other error that keeps happening. I'm sorry if it is some simple thing, i'm a beginner.
This error in particular happens when i try to log in, not register like the other one.

Illuminate \ Contracts \ Encryption \ DecryptException
The payload is invalid.

protected function getJsonPayload($payload)
    {
        $payload = json_decode(base64_decode($payload), true);
 
        // If the payload is not valid JSON or does not have the proper keys set we will
        // assume it is invalid and bail out of the routine since we will not be able
        // to decrypt the given value. We'll also check the MAC for this encryption.
        if (! $this->validPayload($payload)) {
            throw new DecryptException('The payload is invalid.');
        }
 
        if (! $this->validMac($payload)) {
            throw new DecryptException('The MAC is invalid.');
        }
 
        return $payload;
    }

i'm still following this tutorial: https://scotch.io/tutorials/how-to-add-googles-two-factor-authentication-to-laravel

**Comment by nithin-c92** [comment]
This usually happens when google_2fa_secret is empty.
In the User model you can see the key is encrypted and decrypted while storing and getting.
In case null value comes then it throws this error.

**Comment by gurinder-xyrintech** [comment]
> This usually happens when google_2fa_secret is empty.
> In the User model you can see the key is encrypted and decrypted while storing and getting.
> In case null value comes then it throws this error.
> 
> ```
> public function getGoogle2faSecretAttribute($value)
> {
>     return decrypt($value); //error if value empty
> }
> ```

Thanku you so much sir
