### ISSUE TITLE
verifyGoogle2FA() always returns false with getOldOneTimePassword()

### ISSUE THREAD

**Issue by ScottyChung** [antonioribeiro/google2fa-laravel#4]
After setting up the middleware, I had one successful authentication. Coming back later, I no longer could authenticate through the middleware, however my controller implementation still works. 

Digging into things, I found if I don't pass the results from getOldOneTimePassword() then I can authenticate successfully. 
```php
/**
     * Verify the OTP.
     *
     * @return mixed
     */
    protected function verifyGoogle2FA()
    {
        return $this->storeOldOneTimePassord(
            Google2Fa::verifyKey(
                $this->getGoogle2FASecretKey(),
                $this->getOneTimePassword(),
                $this->config('window'),
                null // $timestamp
                //$this->getOldOneTimePassword()
            )
        );
    }
```
getOldOneTimePassword() is returning a null, and I wonder if Google2Fa::verifyKey() can handle that. I also am not sure why I was proceed one time.

**Comment by antonioribeiro** [comment]
Odd, because

It

    protected function storeOldOneTimePassord($key)
    {
        return $this->sessionPut(Constants::SESSION_OTP_TIMESTAMP, $key);
    }

Should return the very same password which was given to it:

    protected function sessionPut($var, $value)
    {
        $this->getRequest()->session()->put(
            $this->makeSessionVarName($var),
            $value
        );

        return $value;
    }

Trying to reproduce this in my end.

**Comment by ScottyChung** [comment]
If I am authenticating for the first time, a null would be expected right?

I'll share more information on my implementation when I get home.

**Comment by ScottyChung** [comment]
So I followed the Middleware instructions of setting up the provider and alias. My view template form looks like the following
```php
<form action="{{Request::url()}}" method="GET">
    <input name="one_time_password" type="text">
    <button type="submit">Authenticate</button>
</form>
```

The requested route is part of a group like the following 
```php
Route::group(['middleware' => ['auth','2fa']], function() {
    Route::get('/home', 'HomeController@index')->name('home');
}
```

**Comment by antonioribeiro** [comment]
Could you please test using dev-master?
I think I got it, it should return Constants::ARGUMENT_NOT_SET instead of null.

**Comment by ScottyChung** [comment]
Looks good. No longer able to reproduce. I appreciate it!
