### ISSUE TITLE
Twice firing event LoginFailed

### ISSUE THREAD

**Issue by Santttal** [antonioribeiro/google2fa-laravel#42]
class Middleware
{
    public function handle($request, Closure $next)
    {
        $authenticator = app(Authenticator::class)->boot($request);

        if ($authenticator->isAuthenticated()) {
            return $next($request);
        }

        return $authenticator->makeRequestOneTimePasswordResponse();
    }
}

First it is firing in isAuthenticated, then in makeRequestOneTimePasswordResponse -> `$this->makeHtmlResponse($this->makeStatusCode())`

**Comment by KevinvanSonsbeek** [comment]
I'm actually running into the same issue. That the login events are being fired twice.
Once by the `isAuthenticated` function, and once by the `makeRequestOneTimePasswordResponse`.
Which is annoying, as i'm trying to log when someone is trying to do the 2fa.
Also having the issue that the LoginFailed event is fired when i load the 2fa page, after entering a wrong code the first time. But it's firing on loading the page, not submitting.
