### ISSUE TITLE
OTP asked for every time, even when laravel session is authenticated from cookie

### ISSUE THREAD

**Issue by nsbucky** [antonioribeiro/google2fa-laravel#43]
The lifetime config value is set to 0, but it always asks. I've cleared the config cache multiple times, but it seems like its not working.

**Comment by antonioribeiro** [comment]
Could not find a bug in the package regarding this, and [tests covering this feature are passing](https://github.com/antonioribeiro/google2fa-laravel/blob/master/tests/Google2FaLaravelTest.php#L177).

If you can reproduce this in a clean app, please ask to reopen.

**Comment by nsbucky** [comment]
ok thanks for looking. I'll take a look at the tests and see if i can figure out my issue.

**Comment by duckarcher** [comment]
This happens because to me too. I will give out some details below.

**Comment by duckarcher** [comment]
Inside `Google2fa.php` there is a method called `twoFactorAuthStillValid`.
This checks if there is a session variable called `auth_passed` in the current session.
(which is put on current session on method login like that: `$this->sessionPut(Constants::SESSION_AUTH_PASSED, true);`)

But if the session ceases to exist, this check will fail and this is the why even if we put a `lifetime` that is more than sessions `lifetime`, the true lifetime of 2FA is the minimum of those two.

This means that by implementing Laravel's `rememberMe` functionality, you can't get the real 2FA experience and it will always depend on the current session instead.

Let me know if I am wrong somewhere and if it's my implementation that creates this limitation for me.

Thank you for your amazing library!

**Comment by JC5** [comment]
This is happening in my applications as well. When the session is dropped or reset, the 2FA validation is gone. A simple call to `\Session::invalidate();` is enough to trigger this from any page.

**Comment by duckarcher** [comment]
I have fixed this behaviour in my project. Had to override the library's middleware. My way is kinda hacky but I tried to keep all the good practices and I have implemented it by using `Cookies` + `Database`. Don't have the time to make a nice and clean PR for it right now, but something similar could be applied by the authors of the library by utilizing those 2.

**Comment by JC5** [comment]
I can't override the middleware for my project. I expect @antonioribeiro to realise this isn't behaving as expected and take it from there.

**Comment by LorenzoSapora** [comment]
“I expect”. 

This is open source. This repositories maintainer isn’t your personal software engineer.

**Comment by JC5** [comment]
Hey, if you want a dick measuring contest I’m game but at least I’m confident enough to acknowledge the problems in my own open source software. 

If you’re all about open source I’d expect you to accept @duckarcher ’s changes. So put up or shut up.
