### ISSUE TITLE
No Lockout on OTP

### ISSUE THREAD

**Issue by devsi** [antonioribeiro/google2fa-laravel#50]
Getting an OTP wrong of course fires an event, but would it be a relevant feature to include an event for OTP lockout after X attempts? I ask because a recent pen test came back with a medium risk flag on OTP facilitating brute force attacks by allowing numerous attempts without repercussions.

This can be remedied by using your events and exceptions, just a thought if it's worth building as a feature of your Middleware.

**Comment by antonioribeiro** [comment]
Isn't this something to be handled by Laravel? Wouldn't it be covered by rate limiting on our routes?

```
'middleware' => 'throttle'
```

**Comment by devsi** [comment]
I guess this is true. I didn't realise I could do this using the existing Throttle middleware. I was able to get it working a few weeks ago in a similar fashion.

```php
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        $authenticator = app(Authenticator::class)->boot($request);

        try {
            if ($authenticator->isAuthenticated()) {
                return $next($request);
            }

            return $authenticator->makeRequestOneTimePasswordResponse();
        } catch (InvalidOneTimePassword $e) {
            $authenticator->logout();
            \Auth::logout();
            return redirect('/login')->withErrors(['message' => $e->getMessage()]);
        }
    }
```
and using exceptions thrown by custom LoginSucceeded and LoginFailed events.

I'm not super sharp on everything Laravel so did not see I could do it as you suggested.

**Comment by antonioribeiro** [comment]
Nice. Added some info to the readme. Thank you!

**Comment by RedmattersBV** [comment]
> I guess this is true. I didn't realise I could do this using the existing Throttle middleware. I was able to get it working a few weeks ago writing my own throttles inside LoginSucceeded and LoginFailed events, and then throwing exceptions, and catching them in this middleware.
> 
> ```
>     /**
>      * Handle an incoming request.
>      *
>      * @param  \Illuminate\Http\Request  $request
>      * @param  \Closure  $next
>      * @return mixed
>      */
>     public function handle($request, Closure $next)
>     {
>         $authenticator = app(Authenticator::class)->boot($request);
> 
>         try {
>             if ($authenticator->isAuthenticated()) {
>                 return $next($request);
>             }
> 
>             return $authenticator->makeRequestOneTimePasswordResponse();
>         } catch (InvalidOneTimePassword $e) {
>             $authenticator->logout();
>             \Auth::logout();
>             return redirect('/login')->withErrors(['message' => $e->getMessage()]);
>         }
>     }
> ```
> 
> I'm not super sharp on everything Laravel so did not see I could do it as you suggested.

Can you show me how you created your own throttles inside LoginSucceeded and LoginFailed events? I wanna do the same but can't figure it out.
