### ISSUE TITLE
Imagick extention

### ISSUE THREAD

**Issue by GoncaloRod** [antonioribeiro/google2fa-laravel#56]
When I try to use features related to BaconQrCode I get this error message `BaconQrCode\Exception\RuntimeException  : You need to install the imagick extension to use this back end` so I installed the Imagick extention on my homestead but it still doesn't work

**Comment by annejan** [comment]
So, what new error message do you get now?
Or did you forgot to restart apache/nginx/php etc?

**Comment by GoncaloRod** [comment]
Same error message, and already restarted everything I can. When I do `phpinfo()` the extension is listed, I really can't understand why it doesn't work.

**Comment by GoncaloRod** [comment]
Downgrading to version 1.0.3 solved the problem for me. It is not a definitive resolution but, it's fine for the time being.
