### ISSUE TITLE
Cannot use an image renderer other than Imagick

### ISSUE THREAD

**Issue by EmilIvanov** [antonioribeiro/google2fa-laravel#58]
While the qrcode Google2FA [constructor](https://github.com/antonioribeiro/google2fa-qrcode/blob/master/src/Google2FA.php#L28) can be passed an ```BaconQrCode\Renderer\Image\ImageBackEndInterface```, its [extension](https://github.com/antonioribeiro/google2fa-laravel/blob/master/src/Google2FA.php#L27) in this repo cannot be passed one. By default an ```BaconQrCode\Renderer\Image\ImagickImageBackEnd``` is created. Is there a reason to limit the abilities of [Bacon/BaconQrCode](https://github.com/Bacon/BaconQrCode#available-image-renderer-back-ends) to only use Imagick as a backend? We're trying not to depend on ImageMagick and had to extend the Authenticator just to change its constructor. The container binding still instantiates the original Authenticator, which is a bummer. A good option would be to have the ```ImageBackEndInterface``` be configurable (e.g. optional constructor arg or  part of the config file).

Thanks and sorry if I'm missing something.

**Comment by sudosammy** [comment]
Would love to see something like this too. I don't want to use this bridge for QRCode generation, nor do I want to install ImageMagic 🙁

**Comment by sudosammy** [comment]
For anyone who stumbles upon this looking to solve a similar problem, this is how I ended up hacking it. Remove the offending class from being autoloaded by composer and specify a location to a patched one:
```
    "autoload": {
        "exclude-from-classmap": [
            "vendor/pragmarx/google2fa-qrcode/src/Google2FA.php"
        ],
        "psr-4": {
            "App\\": "app/",
            "PragmaRX\\Google2FAQRCode\\": "vendor-fixes/pragmarx/google2fa-qrcode/src/"
        }
    },
```
In my case, the patched class looks like this:
```
<?php

namespace PragmaRX\Google2FAQRCode;

use PragmaRX\Google2FA\Google2FA as Google2FAPackage;

class Google2FA extends Google2FAPackage
{
    public function __construct()
    {
        // thank you, next
    }
}
```
Badaboom badabing!
