### ISSUE TITLE
Different Guard?

### ISSUE THREAD

**Issue by mpixelz** [antonioribeiro/google2fa-laravel#67]
Hi,
im trying to implement 2FA to my laravel project based on laravel backpack. Laravel backpack have multiple guards which im using. How can we pass a different guard to our middleware?
Everything is working in terms of registration process but on login it keeps coming back to enter OTP. It never logs me in because of the guard.

**Comment by canstudios-matth** [comment]
@mpixelz Were you able to fix this? If so, how?
