### ISSUE TITLE
Recommended Testing with Middleware Integration

### ISSUE THREAD

**Issue by ScottyChung** [antonioribeiro/google2fa-laravel#8]
I've created some test that use routes with the Middleware integration. I can pass the built-in authentication with
```php
// Authenticate user
$this->be($user);
```
For making request through routes with the tfa middleware, I've just manipulated the session.
```php
// Authenticates 2FA
$this->session(['google2fa' =>
    ['auth_passed' => true]]);
```

This works for my current config with a lifetime of eternal. I was curious if this is a viable process for tests or if there was a more native option?

**Comment by antonioribeiro** [comment]
This way you'll be testing nothing. You can get the current One Time Password and use it to test your app:

    $browser->type('google2fa', $google2fa->getCurrentOtp($user->google2fa_secret))
            ->press('Login')
     ;

**Comment by ScottyChung** [comment]
Ah I see. My objective in these test is not to validate the login, but handle some other logic. Here's an example from a user profile.

```php
public function testUserUsingTFASeesDisableTFANotSetup()
    {
        // Create a new user
        $user = factory(\App\User::class)->make();

        // Set user to use TFA
        $user->using_tfa = true;

        // Authenticate user
        $this->be($user);

        // Authenticates 2FA
        $this->session(['google2fa' =>
            ['auth_passed' => true]]);

        // Get profile page
        $this
            ->get(route('profile'))
            ->assertDontSee('Setup 2-Factor')
            ->assertSee('Disable 2-Factor Auth');
    }
```

**Comment by antonioribeiro** [comment]
If you just want to fake an already passed 2FA, yeah, that should work fine.
