### ISSUE TITLE
Access Level Issues

### ISSUE THREAD

**Issue by DubStepMad** [antonioribeiro/google2fa-laravel#96]
Just recently started to get this.

Running: 
Laravel v 5.8
Ubuntu 16 (Plesk)

`Access level to PragmaRX\Google2FALaravel\Support\Config::config() must be public (as in class PragmaRX\Google2FALaravel\Support\Auth) {"userId":159,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 64): Access level to PragmaRX\\Google2FALaravel\\Support\\Config::config() must be public (as in class PragmaRX\\Google2FALaravel\\Support\\Auth) at /var/www/vhosts/infinitetruckers.com/httpdocs/vendor/pragmarx/google2fa-laravel/src/Google2FA.php:16)`

**Comment by DubStepMad** [comment]
Changed the `config function` to `public` solved this issue.
File: https://github.com/antonioribeiro/google2fa-laravel/blob/master/src/Support/Config.php

I should also mention I am using PHP v 7.4.2

**Comment by TheFrankman** [comment]
Experiencing this also with PHP 7.4.x
Created a fork to change config method to public.
Would be great if this could get resolved in this package soon, don't like maintaining forks if possible

**Comment by Cl1608Ho** [comment]
Bump

**Comment by bgoandoholdings** [comment]
Access level to PragmaRX\Google2FALaravel\Support\Config::config() must be public   
  (as in class PragmaRX\Google2FALaravel\Support\Auth)  :(
